services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      DB_NAME: ${DB_NAME}

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}


  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "15672:15672"
    networks:
      - app-net
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASSWORD}
  scheduler:
    build: ./scheduler
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - app-net
    env_file:
      - .env
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_DEFAULT_USERNAME}
      RABBITMQ_PASS: ${RABBITMQ_DEFAULT_PASSWORD}
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      DB_NAME: ${DB_NAME}

  worker:
    build: ./worker
    depends_on:
      - rabbitmq
      - mongo
      - scheduler
    networks:
      - app-net
    env_file:
      - .env
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASSWORD}
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      DB_NAME: ${DB_NAME}

volumes:
  mongo-data:

networks:
  app-net:
